// Generated by the presentation builder. Edit in the builder, not here.
window.STAGES = [
  {
    id: "content-slide",
    type: "content",
    title: "This is a test",
    quote: "this is a quote\n",
    blurb: "This is also a test ",
    figureCaption: "This is a caption of the figure",
    figure: "media/img-mqe3zwx8-0.png",
    citation: "Vardy (2019)"
  },
  {
    id: "mcq-slide",
    type: "mcq",
    title: "What position do I play?",
    options: [
      {
        id: "option-1",
        label: "Striker ",
        sublabel: "goal machine"
      },
      {
        id: "option-2",
        label: "Midfield",
        sublabel: "wall"
      },
      {
        label: "Goalie",
        id: "new-option",
        sublabel: "stopper"
      }
    ]
  }
];
