// Generated by the presentation builder. Edit in the builder, not here.
window.STAGES = [
  {
    id: "slide-001",
    type: "slide",
    title: "The Future of Sport and Exercise Science: An Interdisciplinary Perspective",
    image: "media/slide-001-mt2x1l79.jpg"
  },
  {
    id: "slide-002",
    type: "slide",
    title: "‘Today’s World Class Performance will be tomorrow’s average. To remain World-class we not only need to learn faster… buthow to perform differently... Nowwe must",
    image: "media/slide-002-mt2x1l79.jpg"
  },
  {
    id: "slide-003",
    type: "slide",
    title: "Three Key Points",
    image: "media/slide-003-mt2x1l79.jpg"
  },
  {
    id: "slide-004",
    type: "slide",
    title: "Exponential functions",
    image: "media/slide-004-mt2x1l79.jpg"
  },
  {
    id: "slide-005",
    type: "slide",
    title: "Spot the difference",
    image: "media/slide-005-mt2x1l79.jpg"
  },
  {
    id: "slide-006",
    type: "slide",
    title: "Disruption and S-Curves",
    image: "media/slide-006-mt2x1l79.jpg"
  },
  {
    id: "slide-007",
    type: "slide",
    title: "Multiple S-Curves of Disruption",
    image: "media/slide-007-mt2x1l79.jpg"
  },
  {
    id: "slide-008",
    type: "slide",
    title: "Learn Faster: A Model of Support",
    image: "media/slide-008-mt2x1l79.jpg"
  },
  {
    id: "slide-009",
    type: "slide",
    title: "Learn Faster: A Model of Support",
    image: "media/slide-009-mt2x1l79.jpg"
  },
  {
    id: "slide-010",
    type: "slide",
    title: "Scientific Support Model: Infrastructure",
    image: "media/slide-010-mt2x1l79.jpg"
  },
  {
    id: "slide-011",
    type: "slide",
    title: "“The pace of innovation is the only thing that matters in the long run”–Elon Musk",
    image: "media/slide-011-mt2x1l79.jpg"
  },
  {
    id: "slide-012",
    type: "slide",
    title: "The raw material",
    image: "media/slide-012-mt2x1l79.jpg"
  },
  {
    id: "slide-013",
    type: "slide",
    title: "Bottlenecks",
    image: "media/slide-013-mt2x1l79.jpg"
  },
  {
    id: "slide-014",
    type: "slide",
    title: "Bottlenecks: Describe",
    image: "media/slide-014-mt2x1l79.jpg"
  },
  {
    id: "slide-015",
    type: "slide",
    title: "Bottlenecks: Analyse",
    image: "media/slide-015-mt2x1l79.jpg"
  },
  {
    id: "slide-016",
    type: "slide",
    title: "Bottlenecks: Prescribe",
    image: "media/slide-016-mt2x1l79.jpg"
  },
  {
    id: "slide-017",
    type: "slide",
    title: "Bottlenecks: Optimise",
    image: "media/slide-017-mt2x1l79.jpg"
  },
  {
    id: "slide-018",
    type: "slide",
    title: "Bottlenecks: Revise",
    image: "media/slide-018-mt2x1l79.jpg"
  },
  {
    id: "slide-019",
    type: "slide",
    title: "Important points",
    image: "media/slide-019-mt2x1l79.jpg"
  },
  {
    id: "slide-020",
    type: "slide",
    title: "CoachAnalyst",
    image: "media/slide-020-mt2x1l79.jpg"
  },
  {
    id: "slide-021",
    type: "slide",
    title: "Integration and Interdisciplinary Practice",
    image: "media/slide-021-mt2x1l79.jpg"
  },
  {
    id: "slide-022",
    type: "slide",
    title: "The problem with data…",
    image: "media/slide-022-mt2x1l79.jpg"
  },
  {
    id: "slide-023",
    type: "slide",
    title: "Interdisciplinary Approaches to Sport and Exercise Science",
    image: "media/slide-023-mt2x1l79.jpg"
  },
  {
    id: "slide-024",
    type: "slide",
    title: "Increasing the pace",
    image: "media/slide-024-mt2x1l79.jpg"
  },
  {
    id: "slide-025",
    type: "slide",
    title: "The Data Cell",
    image: "media/slide-025-mt2x1l79.jpg"
  },
  {
    id: "slide-026",
    type: "slide",
    title: "The Performance Cell",
    image: "media/slide-026-mt2x1l79.jpg"
  },
  {
    id: "slide-027",
    type: "slide",
    title: "Flat organisation",
    image: "media/slide-027-mt2x1l79.jpg"
  },
  {
    id: "slide-028",
    type: "slide",
    title: "Performance Cell",
    image: "media/slide-028-mt2x1l79.jpg"
  },
  {
    id: "slide-029",
    type: "slide",
    title: "The data loop",
    image: "media/slide-029-mt2x1l79.jpg"
  },
  {
    id: "slide-030",
    type: "slide",
    title: "Disruptive technology",
    image: "media/slide-030-mt2x1l79.jpg"
  },
  {
    id: "slide-031",
    type: "slide",
    title: "Disruptive technology",
    image: "media/slide-031-mt2x1l79.jpg"
  },
  {
    id: "slide-032",
    type: "slide",
    title: "Skills development for the future: The Specialist Generalist",
    image: "media/slide-032-mt2x1l79.jpg"
  },
  {
    id: "slide-033",
    type: "slide",
    title: "Skills for an effective performance cell",
    image: "media/slide-033-mt2x1l79.jpg"
  },
  {
    id: "slide-034",
    type: "slide",
    title: "Skills for an effective performance cell",
    image: "media/slide-034-mt2x1l79.jpg"
  },
  {
    id: "slide-035",
    type: "slide",
    title: "Interdisciplinary Ecosystem",
    image: "media/slide-035-mt2x1l79.jpg"
  },
  {
    id: "slide-036",
    type: "slide",
    title: "Effective personal characteristics",
    image: "media/slide-036-mt2x1l79.jpg"
  },
  {
    id: "slide-037",
    type: "slide",
    title: "Three Key Points",
    image: "media/slide-037-mt2x1l79.jpg"
  },
  {
    id: "slide-038",
    type: "slide",
    title: "Interdisciplinary Approaches to Sport and Exercise Science",
    image: "media/slide-038-mt2x1l79.jpg"
  }
];
