// Spec -> files generator for the presentation builder.
//
// This is the in-browser equivalent of the skill's scaffold.py: given a
// presentation spec it returns the text files for one published folder
// (<slug>/). Shells point at the shared ../engine/ and load a per-presentation
// theme.css; engine assets carry a ?v=<version> cache-buster. Media (images)
// are committed separately as binary blobs - this module only lists the
// text files plus presentation.json (the round-trip source of truth).

import { themeCss } from './theme.js';

// The ONE Firebase project shared by every presentation. The engine namespaces
// all data by window.LESSON_ID and the Firestore rules use wildcard matches
// (.+_votes / .+_posters), so a unique LESSON_ID is all a new presentation
// needs - no per-presentation Firebase setup. Keys are public by design.
export const SHARED_FIREBASE_CONFIG = {
  apiKey:            'AIzaSyDYbL0GirWc_zy7XjcKlahbpP89QLVG0m8',
  authDomain:        'worldcupweather.firebaseapp.com',
  projectId:         'worldcupweather',
  storageBucket:     'worldcupweather.firebasestorage.app',
  messagingSenderId: '255510158770',
  appId:             '1:255510158770:web:9ebc10cfe64f6ae3f818ab',
  measurementId:     'G-BQ6G32YXHM'
};

// ---- helpers ---------------------------------------------------------------

function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Render a JS value as a pretty, multi-line JS literal (matches scaffold.py).
export function jsLiteral(v, indent = '') {
  const pad = indent + '  ';
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    return '[\n' + v.map(x => pad + jsLiteral(x, pad)).join(',\n') + '\n' + indent + ']';
  }
  const keys = Object.keys(v).filter(k => v[k] !== undefined);
  if (keys.length === 0) return '{}';
  const parts = keys.map(k => {
    const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
    return pad + key + ': ' + jsLiteral(v[k], pad);
  });
  return '{\n' + parts.join(',\n') + '\n' + indent + '}';
}

function hasMapStage(spec) {
  return (spec.stages || []).some(s => s.type === 'map');
}
function hasPosterStage(spec) {
  return (spec.stages || []).some(s => s.type === 'poster');
}

// ---- individual file builders ----------------------------------------------

// The engine loads the map basemap as `stage.map || 'map.svg'` relative to the
// page. Under the shared-engine model map.svg lives in /engine/, so point map
// stages at ../engine/map.svg (works from both <slug>/ and builder/preview.html).
// Applied only to the generated/previewed STAGES, not to the stored spec, so
// presentation.json stays portable. Use this in BOTH stages.js and the preview.
export function engineStages(stages) {
  return (stages || []).map(s =>
    (s.type === 'map' && !s.map) ? Object.assign({}, s, { map: '../engine/map.svg' }) : s);
}

export function stagesJs(spec) {
  return `// Generated by the presentation builder. Edit in the builder, not here.\n`
    + `window.STAGES = ${jsLiteral(engineStages(spec.stages || []))};\n`;
}

export function lessonConfigJs(spec) {
  return `window.LESSON_ID = ${JSON.stringify(spec.lessonId || spec.slug)};\n`;
}

export function firebaseConfigJs() {
  return `// Shared Firebase project (public keys; security is in Firestore rules).\n`
    + `const FIREBASE_CONFIG = ${jsLiteral(SHARED_FIREBASE_CONFIG)};\n`
    + `const IS_LIVE = FIREBASE_CONFIG.apiKey !== 'REPLACE_ME';\n`
    + `window.FIREBASE_CONFIG = FIREBASE_CONFIG;\n`
    + `window.IS_LIVE = IS_LIVE;\n`;
}

export function citiesJs(spec) {
  if (!spec.cities) return null;
  const bounds = spec.mapBounds || { westLng: 130, eastLng: 60, northLat: 60, southLat: 14 };
  return `const MAP_BOUNDS = ${jsLiteral(bounds)};\n`
    + `const CITIES = ${jsLiteral(spec.cities)};\n`
    + `window.CITIES = CITIES;\nwindow.MAP_BOUNDS = MAP_BOUNDS;\n`;
}

function logoHtml(spec) {
  if (!spec.logo) return '';
  return `<div class="header-logos">\n`
    + `      <img class="brand-logo" src="${esc(spec.logo)}" alt="" onerror="this.style.display='none'">\n`
    + `    </div>`;
}

// version is a cache-buster appended to every asset ref (commit sha or 'dev').
function v(version) { return version ? `?v=${encodeURIComponent(version)}` : ''; }

export function indexHtml(spec, version) {
  const q = v(version);
  const cities = hasMapStage(spec) ? `  <script src="cities.js${q}"></script>\n` : '';
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <meta name="theme-color" content="${esc(spec.theme && spec.theme.paper || '#faf4e6')}">
  <title>${esc(spec.title)} - Vote</title>
  <meta name="description" content="${esc(spec.description || spec.projectorHeading || spec.title)}">
  <meta name="robots" content="noindex">
  <link rel="stylesheet" href="../engine/styles.css${q}">
  <link rel="stylesheet" href="theme.css${q}">
</head>
<body>
  <div id="dev-banner" class="dev-banner" hidden></div>

  <header class="header">
    ${logoHtml(spec)}
    <div class="header-text">
      <div class="kicker">${esc(spec.kicker || '')}</div>
      <h1>${esc(spec.heading || spec.title)}</h1>
    </div>
  </header>

  <main class="main">
    <div id="stage-root"></div>
  </main>

  <script src="lesson.config.js${q}"></script>
${cities}  <script src="stages.js${q}"></script>
  <script src="firebase-config.js${q}"></script>
  <script type="module" src="../engine/store.js${q}"></script>
  <script>
    (function waitForStore() {
      if (window.createStore) {
        var s = document.createElement('script');
        s.src = '../engine/vote.js${q}';
        document.body.appendChild(s);
      } else { setTimeout(waitForStore, 30); }
    })();
  </script>
</body>
</html>
`;
}

export function resultsHtml(spec, version) {
  const q = v(version);
  const cities = hasMapStage(spec) ? `  <script src="cities.js${q}"></script>\n` : '';
  const joinLabel = esc(spec.lessonUrl || (`alanruddock.com/${spec.slug}`));
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${esc(spec.title)} - Projector</title>
  <meta name="robots" content="noindex">
  <link rel="stylesheet" href="../engine/styles.css${q}">
  <link rel="stylesheet" href="theme.css${q}">
  <script src="https://cdn.jsdelivr.net/npm/qrcode@1.5.3/build/qrcode.min.js"></script>
</head>
<body class="projector">
  <div id="dev-banner" class="dev-banner" hidden></div>

  <aside class="qr-corner" aria-label="Join the lesson on your phone">
    <div id="qr-code"></div>
    <div class="qr-corner-label">
      <strong>Vote on your phone</strong>
      <span>${joinLabel}</span>
    </div>
  </aside>

  <header class="header">
    ${logoHtml(spec)}
    <div class="header-text">
      <div class="kicker">${esc(spec.kicker || '')}</div>
      <h1>${esc(spec.projectorHeading || spec.heading || spec.title)}</h1>
    </div>
  </header>

  <main class="main">
    <div id="stage-pane" class="stage-pane"></div>
    <aside id="results-pane" class="results-pane"></aside>
  </main>

  <div class="controls">
    <span id="auth-who" class="auth-who"></span>
    <button id="auth-btn" class="auth-btn" type="button">Sign in to control</button>
    <button id="reset-btn" class="reset" title="Wipe all votes">Reset</button>
    <button id="prev-btn">‹ Back</button>
    <span id="stage-indicator" class="stage-indicator">- / -</span>
    <button id="next-btn">Next ›</button>
  </div>

  <script src="lesson.config.js${q}"></script>
${cities}  <script src="stages.js${q}"></script>
  <script src="firebase-config.js${q}"></script>
  <script type="module" src="../engine/store.js${q}"></script>
  <script>
    (function waitForStore() {
      if (window.createStore) {
        var s = document.createElement('script');
        s.src = '../engine/results.js${q}';
        document.body.appendChild(s);
      } else { setTimeout(waitForStore, 30); }
    })();
  </script>
</body>
</html>
`;
}

// presentation.json = the builder's round-trip source of truth (committed).
export function presentationJson(spec) {
  return JSON.stringify(spec, null, 2) + '\n';
}

// ---- top-level: all text files for one presentation ------------------------

// Returns { files: { '<path>': '<text>' , ... } } where paths are relative to
// the presentation folder. Media binaries are handled by the caller from
// spec.assets. version is the cache-buster (commit sha at publish, 'dev' local).
export function buildPresentationFiles(spec, version) {
  const files = {
    'index.html':         indexHtml(spec, version),
    'results.html':       resultsHtml(spec, version),
    'stages.js':          stagesJs(spec),
    'lesson.config.js':   lessonConfigJs(spec),
    'firebase-config.js': firebaseConfigJs(),
    'theme.css':          themeCss(spec.theme),
    'presentation.json':  presentationJson(spec)
  };
  const cities = citiesJs(spec);
  if (cities) files['cities.js'] = cities;
  // Poster shells are v2; flag so the caller/UI can warn if a poster stage slips in.
  return { files, hasPoster: hasPosterStage(spec), hasMap: hasMapStage(spec) };
}
